development:
  password: shptka_706e95a7d69e6d6307b748d835e670a7
  theme_id: "145796235487"
  store: shambhavi-studio.myshopify.com
  ignore_files:
  - config/settings_data.json
  - README.md
  - .gitignore
  - templates/*.json #ignoring these JSON files to prevent overriding Theme settings
  - sections/*.json #ignoring these JSON files to prevent overriding Theme settings
  - "*.png"
  - "*.jpg" 
  - "*.jpeg" 
  - "*.svg" 
  - "*.gif"
  - "*.js.map"
  - "*.mp4"
  - /index.sbkit*/
  - assets/bundle.js.map

production:
  password: shptka_706e95a7d69e6d6307b748d835e670a7
  theme_id: "145675780319"
  store: shambhavi-studio.myshopify.com
  ignore_files:
  - config/settings_data.json
  - README.md
  - .gitignore
  - templates/*.json #ignoring these JSON files to prevent overriding Theme settings
  - sections/*.json #ignoring these JSON files to prevent overriding Theme settings
  - "*.png"
  - "*.jpg" 
  - "*.jpeg" 
  - "*.svg" 
  - "*.gif"
  - "*.mp4"
  - "*.js.map"
  - /index.sbkit*/
  - assets/bundle.js.map